### ISSUE TITLE
StreamDeck connection error

### ISSUE THREAD

**Issue by RZethraus** [bitfocus/companion-module-generic-http#48] opened 2023-10-03 19:09 UTC
Start Companion, Look at Connections tab.  Module is http Generic, Status is Green and error is green.

Push a button on StreamDeck and Status changes to. ERROR - EConnRefused.

Any help?

**Comment by Julusian** [comment] 2023-11-08 18:18
This means that your request failed, or returned a non 2xx status code.

As this is not a bug in the module, I am closing this

**Closed by Julusian** 2023-11-08 18:18 UTC
